### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by ppg** [akio/rosgo_core#1]
@akio I'm interested in using go with ROS and potentially updating all these bits and pieces, but I can't figure out where to get started with the current rosgo stuff. I hacked directly into rosgo_core and can start a subscriber, but I can't figure out how to generate go files for messages. Any pointers you have that could help?

Thanks,
\Peter

**Comment by akio** [comment]
Hi Peter,

I'm happy to your interest in rosgo.

Message generation is integrated with catkin/genmsg.
So you don't need any special trick, just call `add_message_files()` in your `CMakeLists.txt`.
I think the best example at this point is `rosgo_tests/CMakeLists.txt`.
At present, you have to generate well-known messages like `geometry_msgs` from source except `std_msgs` and `rosgraph_msgs`. 
This problem will be solved in the future with `rosgo_messages` package.

I had been short of time for open source activity last year. 
But it's good time to make me back to development. 
Thank you for creating this issue.

Sincerely,
akio

**Comment by ppg** [comment]
Hi akio,

Thanks for getting back. I think I'm actually having numerous issues:
1. What is the correct way to 'install' rosgo? I'm on OSX, so I'm building ros (jade) from source and what I ended up doing (not sure if its right) is adding in the various rosgo stuff to my `.rosinstall` file and then have it build things into my installation at `/opt/ros/jade`. This is what I added in there:
   
   ```
   # PPG: add rosgo stuff
   - tar:
       local-name: gengo
       #uri: https://github.com/akio/gengo/archive/master.tar.gz
       uri: https://github.com/akio/gengo
       version: master
   - tar:
       local-name: rosgo
       uri: https://github.com/akio/rosgo/archive/master.tar.gz
       version: master
   - tar:
       local-name: rosgo_build_tools
       uri: https://github.com/akio/rosgo_build_tools/archive/master.tar.gz
       version: master
   - tar:
       local-name: rosgo_core
       uri: https://github.com/akio/rosgo_core/archive/master.tar.gz
       version: master
   - tar:
       local-name: rosgo_messages
       uri: https://github.com/akio/rosgo_messages/archive/master.tar.gz
       version: master
   ```
   
   Is this correct? Should I be installing another way?
2. In my go code, I'm importing `"github.com/akio/rosgo/src/ros"` as that's where I did go get on rosgo; does that sound correct? It appears to at least allow the golang stuff to compile.
3. When I try to add in the appropriate lines to the catkin make system, I still get an error: 
   
   ```
   - ==> add_subdirectory(lisa)
   -- Using these message generators: gencpp;geneus;gengo;genlisp;genpy
   CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
     Could not find a package configuration file provided by "rosgo" with any of
     the following names:
   
       rosgoConfig.cmake
       rosgo-config.cmake
   
     Add the installation prefix of "rosgo" to CMAKE_PREFIX_PATH or set
     "rosgo_DIR" to a directory containing one of the above files.  If "rosgo"
     provides a separate development package or SDK, be sure it has been
     installed.
   Call Stack (most recent call first):
     lisa/CMakeLists.txt:7 (find_package)
   
   
   -- Configuring incomplete, errors occurred!
   See also "/Users/ppgengler/projects/avc/lisa/build/CMakeFiles/CMakeOutput.log".
   make: *** [cmake_check_build_system] Error 1
   Invoking "make cmake_check_build_system" failed
   ```
   
   I can't figure out what part I'm missing; we have a public branch with this at: https://github.com/weird-science-avc/lisa/tree/rosgo that one could try to run `catkin_make` in. The pertinent lines (I think) are:
   - https://github.com/weird-science-avc/lisa/blob/rosgo/src/lisa/CMakeLists.txt#L11
   - https://github.com/weird-science-avc/lisa/blob/rosgo/src/lisa/CMakeLists.txt#L74-L77
   - https://github.com/weird-science-avc/lisa/blob/rosgo/src/lisa/CMakeLists.txt#L95
   - https://github.com/weird-science-avc/lisa/blob/rosgo/src/lisa/CMakeLists.txt#L138-L140

Any thoughts on where to go for me?

Thanks,
\Peter
